name: annotation
channels:
  - defaults
  - conda-forge
  - pyviz
  - bokeh
dependencies:
  - jupyter-panel-proxy
  - python=3.7*
  - pip=20.3*
  - bokeh=2.2.3
  - datashader
  - numpy=1.19.2
  - pandas=1.2.1
  - panel=0.10.3
  - param=1.10.1
  - scipy=1.6.0
  - xarray=0.16.2
