name: annotation
channels:
  - defaults
  - conda-forge
  - pyviz
  - bokeh
dependencies:
  - jupyter-panel-proxy
  - python=3.7*
  - pip=20.3*
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - bokeh=2.2.3
  - brotlipy=0.7.0
  - ca-certificates
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - click=7.1.2
  - cloudpickle
  - colorama=0.4.4
  - colorcet=2.0.6
  - cryptography=3.3.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.1.1
  - dask-core
  - datashader
  - datashape
  - decorator
  - defusedxml
  - distributed
  - entrypoints
  - freetype
  - fsspec
  - heapdict
  - holoviews
  - icc_rt
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.3.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - llvmlite=0.34.0
  - locket=0.2.1
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - msgpack-python=1.0.2
  - msys2-conda-epoch=20160418
  - multipledispatch=0.6.0
  - nbclient=0.5.1
  - nbconvert=5.5.0
  - nbformat=5.1.2
  - nest-asyncio=1.4.3
  - notebook=5.7.10
  - numba=0.51.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - packaging=20.9
  - pandas=1.2.1
  - pandoc=2.11
  - pandocfilters=1.4.3
  - panel=0.10.3
  - param=1.10.1
  - parso=0.8.1
  - partd=1.1.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - psutil=5.8.0
  - pycparser=2.20
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pygments=2.7.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2021.1
  - pyviz_comms=2.0.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - requests=2.25.1
  - scipy=1.6.0
  - send2trash=1.5.0
  - setuptools=52.0.0
  - six=1.15.0
  - sortedcontainers=2.3.0
  - sqlite=3.33.0
  - tblib=1.7.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.56.0
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - tzdata=2020f
  - urllib3=1.26.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xarray=0.16.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
