name: annotation
channels:
  - defaults
  - conda-forge
  - pyviz
  - bokeh
dependencies:
  - jupyter-panel-proxy
  - python=3.7*
  - pip=20.3*
  - bokeh=2.2.3
  - datashader
  - numpy=1.19.2
  - pandas=1.2.1
  - panel=0.10.3
  - param=1.10.1
  - pillow=8.1.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - psutil=5.8.0
  - pycparser=2.20
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pygments=2.7.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2021.1
  - pyviz_comms=2.0.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - requests=2.25.1
  - scipy=1.6.0
  - send2trash=1.5.0
  - setuptools=52.0.0
  - six=1.15.0
  - sortedcontainers=2.3.0
  - sqlite=3.33.0
  - tblib=1.7.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.56.0
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - tzdata=2020f
  - urllib3=1.26.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - xarray=0.16.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
